"""Export one bench run as the website's data module: per-question grape vs vector RAG numbers.

Usage: python3 tools/export_site.py results/<run>.json > ../../react/grape-web/src/data/heldout.ts
The site's source is ASCII-only, so text is transliterated and trimmed.
"""

import json
import re
import sys
import unicodedata
from pathlib import Path


def ascii_text(s, limit=None):
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode()
    s = re.sub(r"\s+", " ", s.replace("**", "")).strip()
    return s if not limit or len(s) <= limit else s[: limit - 3].rstrip() + "..."


# Questions in scripts that don't transliterate to ASCII, shown as an English gloss.
GLOSS = {"\u0911\u0915\u094d\u091f\u094b\u092a\u0938 \u0915\u0947 \u0915\u093f\u0924\u0928\u0947 \u0926\u093f\u0932 \u0939\u094b\u0924\u0947 \u0939\u0948\u0902?": "(Hindi) How many hearts does an octopus have?"}


def side(r, keep_route):
    out = {k: r[k] for k in ("in", "out", "cost", "calls", "seconds", "correct")}
    out["answer"] = ascii_text(r.get("answer", ""), 220)
    if keep_route:
        out["route"] = r.get("route", "direct")
    return out


src = Path(sys.argv[1])
run = json.loads(src.read_text())
data = {
    "run": src.stem,
    "model": run["model"],
    "setup": run["setup_seconds"],
    "rows": [
        {"q": GLOSS.get(r["q"]) or ascii_text(r["q"]), "type": r["type"], "grape": side(r["grape"], True), "rag": side(r["rag"], False)}
        for r in run["rows"]
    ],
}
print("// Generated by grape-bench/tools/export_site.py from " + src.name + ". Do not edit by hand.")
print("export const heldout = " + json.dumps(data, indent=2) + ";")
